POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "toyota",
    "model": "corola",
    "price": 1000000,
    "mileage": 3000,
    "lat": 0,
    "lng": 0,
    "year": 2010
}

### Approve a report
PATCH http://localhost:3000/reports/9
Content-Type: application/json

{
    "isApproved": true
}

### Get estimates for price
GET http://localhost:3000/reports?make=toyota&model=corola&year=2010&lat=0&lng=0&mileage=3000